backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
    - name: "productos"
    label: "Productos"
    folder: "content/productos"
    create: true
    slug: "{{slug}}"
    fields:
            - {label: "Nombre del Producto", name: "title", widget: "string"}
            - {label: "Precio S/", name: "precio", widget: "number"}
            - {label: "Descripción", name: "body", widget: "text"}
            - {label: "Imagen", name: "image", widget: "image"}
