backend:
 name: git-gateway
 branch: main
media_folder: public/uploads
public_folder: /uploads
collections:
    - name: menu
    label: Menu D'Pochis
    folder: content/menu
    create: true
    fields:
            - {label: Nombre, name: title, widget: string}
            - {label: Precio, name: precio, widget: number}
            - {label: Descripcion, name: body, widget: text}
            - {label: Imagen, name: image, widget: image}
